name: strategy matrix
on:
  workflow_dispatch:

jobs:
  test_node-setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        node: [6, 8, 10]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: inspection
        run: |
          cat /etc/os-release
          echo
          node version
